# Generated by Django 3.1.4 on 2021-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reference',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
