# Generated by Django 3.1.4 on 2021-01-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210104_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='url',
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
