# Generated by Django 3.1.4 on 2021-07-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_image')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store')),
            ],
        ),
    ]
