# Generated by Django 3.1.4 on 2021-06-18 10:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210618_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
