# Generated by Django 3.1.4 on 2021-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210618_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
