# Generated by Django 3.1.4 on 2021-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210618_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
