# Generated by Django 3.1.4 on 2021-06-18 18:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210618_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='item_image'),
        ),
    ]
