# Generated by Django 3.1.4 on 2021-06-18 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210618_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='item_image'),
            preserve_default=False,
        ),
    ]
