# Generated by Django 3.1.4 on 2021-06-18 18:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20210618_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='item_image'),
        ),
    ]
