# Generated by Django 3.1.4 on 2021-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
