# Generated by Django 3.1.4 on 2021-05-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
