# Generated by Django 3.1.4 on 2021-05-03 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210503_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
