# Generated by Django 3.1.4 on 2021-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_reviewstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstore',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
