# Generated by Django 3.1.4 on 2021-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_reviewstore_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='account_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='bank_name',
            field=models.CharField(default='Access Bank', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
            preserve_default=False,
        ),
    ]
