# Generated by Django 3.1.4 on 2021-06-18 18:32

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='store_image'),
            preserve_default=False,
        ),
    ]
