# Generated by Django 3.1.4 on 2021-06-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20210618_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(upload_to='store_image'),
        ),
    ]
