# Generated by Django 3.1.4 on 2021-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_auto_20210619_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
    ]
