# Generated by Django 3.1.4 on 2021-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='losales_commission',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_commission',
            field=models.BigIntegerField(default=0),
        ),
    ]
