# Generated by Django 3.1.4 on 2021-06-06 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210606_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
